# Generated by Django 5.0.1 on 2024-01-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_thumbnail_detail_souhait'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.FloatField(default=0.0),
        ),
    ]
