# Generated by Django 5.0.1 on 2024-01-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_old_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail_detail',
            new_name='thumbnail2',
        ),
    ]
