# Generated by Django 5.0.1 on 2024-01-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_thumbnail_detail_product_thumbnail2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail2',
            new_name='thumbnail_detail',
        ),
    ]
